title = "The Update Framework"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
baseURL = "https://theupdateframework.io"

[markup.goldmark.renderer]
unsafe = true

[params]
font_awesome_version = "5.12.0"
description = "A framework for securing software update systems"
favicon = "favicon.png"
copyright = """
The TUF project is managed by the Linux Foundation under the Cloud Native Computing Foundation. The consensus builder for TUF is [Prof. Justin Cappos](https://ssl.engineering.nyu.edu/personalpages/jcappos/) of the [Secure Systems Lab](https://ssl.engineering.nyu.edu) at [New York University](https://engineering.nyu.edu/). Maintainers include [Sebastien Awwad](https://github.com/awwad) of [CONDA](https://docs.conda.io/en/latest) and [Lukas PÃ¼hringer](https://github.com/lukpueh), also of NYU's Secure Systems Lab. Contributors and maintainers are governed by the [CNCF Community Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md).

This material is based upon work supported by the National Science Foundation under Grant Nos. CNS-1345049 and CNS-0959138. Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation.
"""

[params.logos]
navbar = "tuf-horizontal-white.png"
hero = "tuf-stacked-color.png"
cncf = "cncf-color.png"

[[params.fonts]]
name = "Nunito"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[menu.main]]
name = "About"
identifier = "about"
weight = 1

[[menu.main]]
name = "Overview"
parent = "about"
url = "/overview"
weight = 1

[[menu.main]]
name = "History"
parent = "about"
url = "/history"
weight = 2

[[menu.main]]
name = "Timeline"
parent = "about"
url = "/timeline"
weight = 3

[[menu.main]]
name = "Publications"
parent = "about"
url = "/publications"
weight = 5

[[menu.main]]
name = "People"
parent = "about"
url = "/people"
weight = 5

[[menu.main]]
name = "Code of conduct"
parent = "about"
url = "https://github.com/cncf/foundation/blob/master/code-of-conduct.md"
weight = 6

[[menu.main]]
name = "Getting started"
identifier = "getting-started"
weight = 2

[[menu.main]]
name = "Security"
parent = "getting-started"
url = "/security"
weight = 1

[[menu.main]]
name = "Roles and metadata"
parent = "getting-started"
url = "/metadata"
weight = 2

[[menu.main]]
name = "Frequently asked questions"
parent = "getting-started"
url = "/faq"
weight = 3

[[menu.main]]
name = "Specification (latest)"
parent = "getting-started"
url = "https://theupdateframework.github.io/specification/latest/"
weight = 4

[[menu.main]]
name = "Specification index"
parent = "getting-started"
url = "https://theupdateframework.github.io/specification/"
weight = 5


[[menu.main]]
name = "Implementation"
parent = "getting-started"
url = "https://github.com/theupdateframework/tuf/blob/develop/docs/GETTING_STARTED.rst#getting-started"
weight = 6

[[menu.main]]
name = "Videos"
parent = "getting-started"
url = "/videos"
weight = 7

[[menu.main]]
name = "Community"
identifier = "community"
weight = 3

[[menu.main]]
name = "Adoptions"
parent = "community"
url = "/adoptions"
weight = 1

[[menu.main]]
name = "Reporting issues"
parent = "community"
url = "/reporting"
weight = 2

[[menu.main]]
name = "Security audits"
parent = "community"
url = "/audits"
weight = 3

[[menu.main]]
name = "Enhancement proposals"
parent = "community"
url = "/taps"
weight = 4

[[menu.main]]
name = "Contribute"
parent = "community"
url = "https://github.com/theupdateframework/tuf"
weight = 5

[[menu.main]]
name = "News"
url = "/news/"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5
